version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_sistema_vendas
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sistema_vendas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_sistema_vendas
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/sistema_vendas
    volumes:
      - ./app:/code/app

volumes:
  postgres_data:
